# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "idx", # <tidy.NebulaSE>
  "convergence", # <tidy.NebulaSE>
  "term", # <tidy.NebulaSE>
  "quantity", # <tidy.NebulaSE>
  "logFC", # <tidy.NebulaSE>
  "se", # <tidy.NebulaSE>
  "p", # <tidy.NebulaSE>
  "p.value", # <tidy.NebulaSE>
  "idx", # <add_gene_name>
  ".data", # <gresults.NebulaSE>
  "estimate", # <gresults.NebulaSE>
  "p.value", # <gresults.NebulaSE>
  "p.adjusted", # <gresults.NebulaSE>
  "estimate", # <do_nebula_contrasts>
  "p.value", # <do_nebula_contrasts>
  NULL
))
